spring:
  application:
    name: ${project.artifactId}
camel:
  springboot:
    name: ${project.artifactId}
  rest:
    port: 9000
    context-path: /api
management:
  endpoint:
    camelroutes:
      enabled: true
      read-only: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,camelroutes